config/routes.rb
Rails.application.routes.draw do
  root 'spaces#index'

  resources :spaces
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/space.rb
class Space < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
    before_action :set_space, only: [:show, :edit, :update, :destroy]

    def index
        @spaces = Space.all
    end

    def show
       
    end
    

    def new
        @space = Space.new
    end

    def create
        @space = Space.new(space_params)
            if @space.save
                flash[:success] = "Space has been created."
                redirect_to spaces_url
            else
                flash[:alert] = "Space has not been created."
            render 'new'
        end
    end

    private

    def set_space
        @space = Space.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:alert] = 'The space you were looking for could not be found.'
        redirect_to spaces_path
    end

    def space_params
        params.require(:space).permit(:title, :category, :phone, :location, :description)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Travel</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<% flash.each do |key, message| %>
<div class="alert alert-<%= key %>">
	<%= message %>
</div>
<% end %>

<%= yield %>

</html>

app/views/spaces/_form.html.erb
<%= simple_form_for @space do |f| %>
<%= f.input :title %>
<%= f.input :category %>
<%= f.input :phone %>
<%= f.input :location %>
<%= f.input :description, as: :text %>

<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/spaces/index.html.erb
<%= link_to  "New Space", new_space_path %>

<% @spaces.each do |space| %>
<h2><%= link_to  space.title, space %></h2>
<% end %>

app/views/spaces/new.html.erb
<header>
	<h1>
		New Space
	</h1>
</header>

<%= render "form", space: @space %>

app/views/spaces/show.html.erb
<h1><%= @space.title %></h1>

<table style="width:100%">
	<tr>
		<th>Category</th>
		<th>Phone</th>
		<th>Location</th>
		<th>Description</th>
	</tr>
	<tr>
		<td><%= @space.category %></td>
		<td><%= @space.phone %></td>
		<td><%= @space.location %></td>
		<td><%= @space.description %></td>
	</tr>
</table>